name: Main
on: push
jobs:
  linux: 
    runs-on: ubuntu-latest
    steps:
    - name: clone
      shell: bash
      run: |
        sudo apt update && sudo apt install git
        cd $GITHUB_WORKSPACE
        git clone https://github.com/riscv-collab/riscv-gnu-toolchain.git
    - name: compile
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/riscv-gnu-toolchain
        mkdir $GITHUB_WORKSPACE/build
        sudo apt-get install -y autoconf automake autotools-dev curl python3 python3-pip python3-tomli libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev libslirp-dev
        ./configure --prefix=$GITHUB_WORKSPACE/build --enable-multilib
        make -j4
        make install
    - name: pack
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/build
        mkdir DEBIAN
        echo "Package:riscv-gnu-toolchain
        Version:20250522
        Architecture:amd64
        Maintainer: Mike Solar
        Description: GCC for RISC-V, use Newlib" > DEBIAN/control
        cd ..
        dpkg -b build riscv-gcc.deb
    - name: Archive production artifacts
        uses: actions/upload-artifact
        with:
          name: build-artifacts
          path: $GITHUB_WORKSPACE/riscv-gcc.deb
    - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: $GITHUB_WORKSPACE/riscv-gcc.deb
          tag_name: 20250522
